[package]
name = "cc-switch-tui"
version = "0.8.1"
edition = "2024"
default-run = "cc-switch-tui"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
rusqlite = { version = "0.32", features = ["bundled"] }
dirs = "5"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
ureq = { version = "3.3.0", features = ["platform-verifier"] }
serde = { version = "1.0.228", features = ["derive"] }

# ys-proxy 引入
reqwest = { version = "0.12", features = ["json", "stream"] }
futures = "0.3"
bytes = "1"
uuid = { version = "1", features = ["v4"] }

# S0 引入
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "net", "time"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
include_dir = "0.7"
webbrowser = "1"
mime_guess = "2"

[dev-dependencies]
tempfile = "3"
reqwest = { version = "0.12", features = ["json"] }
