import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { AliasesPreview } from '../AliasesPreview';

const SAMPLE = `# Auto-generated by cc-switch-tui. Do not edit manually.
emulate zsh
function cl-mini {
  unset ANTHROPIC_AUTH_TOKEN
  export ANTHROPIC_BASE_URL=https://api.minimaxi.com/anthropic
  export ANTHROPIC_AUTH_TOKEN=sk-test-1234-abcdef
  export ANTHROPIC_MODEL=MiniMax-M2.7-highspeed
  command claude "$@"
}
function oc-mini {
  unset MINIMAX_API_KEY
  export MINIMAX_API_KEY=minimax-secret-9999
  command opencode "$@"
}`;

describe('AliasesPreview', () => {
  function getText() {
    return document.body.textContent ?? '';
  }

  it('masks sensitive values by default', () => {
    render(<AliasesPreview content={SAMPLE} />);
    const text = getText();
    expect(text).toMatch(/sk-\*+[a-z0-9]{0,4}/);
    expect(text).toMatch(/min\*+9999/);
    // 非敏感行原样
    expect(text).toContain('export ANTHROPIC_BASE_URL=https://api.minimaxi.com/anthropic');
  });

  it('does not leak the full secret by default', () => {
    render(<AliasesPreview content={SAMPLE} />);
    const text = getText();
    expect(text).not.toContain('sk-test-1234-abcdef');
    expect(text).not.toContain('minimax-secret-9999');
  });

  it('reveals secrets after clicking the toggle', async () => {
    const user = userEvent.setup();
    render(<AliasesPreview content={SAMPLE} />);
    const button = screen.getByRole('button', { name: /reveal/i });
    await user.click(button);
    const text = getText();
    expect(text).toContain('sk-test-1234-abcdef');
    expect(text).toContain('minimax-secret-9999');
  });

  it('hides secrets again when toggle is clicked twice', async () => {
    const user = userEvent.setup();
    render(<AliasesPreview content={SAMPLE} />);
    const button = screen.getByRole('button', { name: /reveal/i });
    await user.click(button);
    await user.click(screen.getByRole('button', { name: /hide/i }));
    const text = getText();
    expect(text).not.toContain('sk-test-1234-abcdef');
  });
});
