use crate::domain::{ProviderInstance, ProviderTemplate};
use crate::opencode_config;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// 渲染 aliases.zsh 内容（不写盘，不生成 opencode 配置文件）。
/// 供 Web 预览使用。
pub fn render_aliases(instances: &[ProviderInstance], templates: &[ProviderTemplate]) -> String {
    let mut lines = vec![
        "# Auto-generated by cc-switch-tui. Do not edit manually.".to_string(),
        "emulate zsh".to_string(),
    ];

    let all_env_vars = get_all_env_vars(templates);

    for instance in instances {
        if instance.alias.is_empty() {
            continue;
        }
        let env = build_env(instance, templates);
        let function_def = format_function(
            &instance.alias,
            &env,
            &all_env_vars,
            instance.kv_cache_enabled,
        );
        lines.push(function_def);
    }

    // 包含 opencode alias 引用（不写 opencode 配置文件本身）
    // 这里我们需要 config_paths，但因为不写盘，所以用占位符
    // 简化：直接复用 build_opencode_aliases 但传空 paths（生成的 alias 引用本地路径）
    let dummy_paths: HashMap<String, PathBuf> = instances
        .iter()
        .filter(|i| !i.alias.is_empty())
        .map(|i| {
            (
                i.alias.clone(),
                PathBuf::from(format!("~/.cc-switch-tui/opencode/{}.json", i.alias)),
            )
        })
        .collect();
    let opencode_lines =
        opencode_config::build_opencode_aliases(instances, templates, &dummy_paths);
    lines.extend(opencode_lines);

    lines.join("\n") + "\n"
}

/// 写入 aliases.zsh 到 dir/aliases.zsh（不生成 opencode 配置文件）。
pub fn write_aliases(dir: &Path, content: &str) -> std::io::Result<PathBuf> {
    fs::create_dir_all(dir)?;
    let path = dir.join("aliases.zsh");
    fs::write(&path, content)?;
    Ok(path)
}

/// 生成 aliases.zsh 文件（同时生成 cl-* 和 oc-* alias，**并**生成 opencode 配置文件）。
/// 保留向后兼容 — main.rs 启动时预生成时仍调用。
pub fn generate_aliases(
    dir: &std::path::Path,
    instances: &[ProviderInstance],
    templates: &[ProviderTemplate],
) -> std::io::Result<()> {
    let content = render_aliases(instances, templates);

    // 同时生成 opencode 配置文件
    let _config_paths = opencode_config::generate_opencode_configs(dir, instances, templates)?;

    write_aliases(dir, &content)?;
    Ok(())
}

fn build_env(
    instance: &ProviderInstance,
    templates: &[ProviderTemplate],
) -> HashMap<String, String> {
    let mut env = HashMap::new();
    if let Some(template) = templates.iter().find(|t| t.id == instance.template_id) {
        env.extend(template.default_env.clone());
        if let Some(model) = template.models.iter().find(|m| m.id == instance.model_id) {
            env.extend(model.env_overrides.clone());
        }
    }
    // 若实例开启了 context window 且模型有预设值，注入相关环境变量
    if instance.context_window_enabled {
        if let Some(template) = templates.iter().find(|t| t.id == instance.template_id) {
            if let Some(model) = template.models.iter().find(|m| m.id == instance.model_id) {
                if let Some(window) = model.context_window {
                    env.insert("DISABLE_COMPACT".to_string(), "1".to_string());
                    env.insert("CLAUDE_CODE_MAX_CONTEXT_TOKENS".to_string(), window.to_string());
                    env.insert("CLAUDE_CODE_AUTO_COMPACT_WINDOW".to_string(), window.to_string());
                }
            }
        }
    }
    env.insert("ANTHROPIC_AUTH_TOKEN".to_string(), instance.api_key.clone());
    env.insert(
        "CMUX_PRESERVE_CLAUDE_AUTH_SELECTION_ENV".to_string(),
        "1".to_string(),
    );
    env.insert("CC_SWITCH_ALIAS".to_string(), instance.alias.clone());
    env
}

/// 收集所有需要 unset 的环境变量（来自所有模板）
fn get_all_env_vars(templates: &[ProviderTemplate]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::from([
        "ANTHROPIC_AUTH_TOKEN".to_string(),
        "CMUX_PRESERVE_CLAUDE_AUTH_SELECTION_ENV".to_string(),
        "CC_SWITCH_ALIAS".to_string(),
        "DISABLE_COMPACT".to_string(),
        "CLAUDE_CODE_MAX_CONTEXT_TOKENS".to_string(),
        "CLAUDE_CODE_AUTO_COMPACT_WINDOW".to_string(),
    ]);
    for template in templates {
        set.extend(template.default_env.keys().cloned());
        for model in &template.models {
            set.extend(model.env_overrides.keys().cloned());
        }
    }
    let mut vars: Vec<String> = set.into_iter().collect();
    vars.sort();
    vars
}

fn format_function(
    name: &str,
    env: &HashMap<String, String>,
    unset_vars: &[String],
    kv_cache_enabled: bool,
) -> String {
    let mut pairs: Vec<_> = env.iter().collect();
    pairs.sort_by(|a, b| a.0.cmp(b.0));

    let unset_line = format!("  unset {}", unset_vars.join(" "));

    let export_lines: String = pairs
        .iter()
        .map(|(k, v)| format!("  export {}={}", k, shell_escape(v)))
        .collect::<Vec<_>>()
        .join("\n");

    let claude_cmd = if kv_cache_enabled {
        "command claude --exclude-dynamic-system-prompt-sections --settings '{\"includeGitInstructions\":false}' \"$@\""
    } else {
        "command claude \"$@\""
    };

    format!(
        "function {} {{\n{}\n{}\n  {}\n}}",
        name, unset_line, export_lines, claude_cmd
    )
}

pub(crate) fn shell_escape(s: &str) -> String {
    if s.contains('\'') {
        format!("'{}'", s.replace('\'', "'\"'\"'"))
    } else if s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "_.:-/".contains(c))
    {
        s.to_string()
    } else {
        format!("'{}'", s)
    }
}

/// 检查 zshrc 文件是否包含 source ~/.cc-switch-tui/aliases.zsh
pub fn ensure_zshrc_source(zshrc_path: &std::path::Path) -> std::io::Result<bool> {
    let source_line = "source ~/.cc-switch-tui/aliases.zsh";
    if zshrc_path.exists() {
        let content = fs::read_to_string(zshrc_path)?;
        if content.lines().any(|l| l.trim() == source_line) {
            return Ok(false);
        }
    }
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(zshrc_path)?;
    writeln!(file, "{}", source_line)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{ModelTemplate, ProviderTemplate};
    use std::collections::HashMap;
    use tempfile::TempDir;

    #[test]
    fn test_generate_aliases_creates_file() {
        let temp = TempDir::new().unwrap();
        let instances: Vec<ProviderInstance> = vec![];
        let templates: Vec<ProviderTemplate> = vec![];
        generate_aliases(temp.path(), &instances, &templates).unwrap();
        assert!(temp.path().join("aliases.zsh").exists());
    }

    #[test]
    fn test_generate_aliases_content() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
                context_window: None,
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M2.7-highspeed".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed-cl-mini".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
            opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            kv_cache_enabled: false,
            context_window_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // 新格式：函数格式，包含 unset 和 export
        assert!(content.contains("function cl-mini {"));
        assert!(content.contains("unset"));
        assert!(content.contains("export"));
        assert!(content.contains("command claude \"$@\""));
    }

    #[test]
    fn test_generate_aliases_contains_unset_vars() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
                context_window: None,
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M2.7-highspeed".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed-cl-mini".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
            opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            kv_cache_enabled: false,
            context_window_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // 验证函数格式：包含 unset 和 export
        assert!(content.contains("unset ANTHROPIC_AUTH_TOKEN"));
        assert!(content.contains("export ANTHROPIC_AUTH_TOKEN=sk-test"));
        // 验证 CC_SWITCH_ALIAS 同时出现在 unset 和 export 中
        assert!(content.contains("CC_SWITCH_ALIAS"));
        assert!(content.contains("export CC_SWITCH_ALIAS=cl-mini"));
    }

    #[test]
    fn test_generate_aliases_kv_cache_enabled() {
        let temp = TempDir::new().unwrap();
        let template = ProviderTemplate {
            id: "llama".to_string(),
            name: "Llama.cpp".to_string(),
            default_env: HashMap::new(),
            models: vec![ModelTemplate {
                id: "qwen3-27b".to_string(),
                name: "Qwen3 27B".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "qwen3-27b".to_string(),
                context_window: None,
            }],
            opencode_provider_id: String::new(),
            opencode_npm: String::new(),
            opencode_base_url: String::new(),
            opencode_env_var: String::new(),
            opencode_models: vec!["qwen3-27b".to_string()],
        };
        let instance = ProviderInstance {
            id: "llama-qwen3-27b-cl-local".to_string(),
            template_id: "llama".to_string(),
            model_id: "qwen3-27b".to_string(),
            api_key: "no-key".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-local".to_string(),
            opencode_model_id: "qwen3-27b".to_string(),
            kv_cache_enabled: true,
            context_window_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // Verify KV cache parameters are present
        assert!(content.contains("--exclude-dynamic-system-prompt-sections"));
        assert!(content.contains("includeGitInstructions"));
        assert!(content.contains("command claude --exclude-dynamic-system-prompt-sections"));
    }

    #[test]
    fn test_build_env_injects_context_window_vars() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M3".to_string(),
                name: "MiniMax M3".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M3".to_string(),
                context_window: Some(1_000_000),
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M3".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M3-cl-m3".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M3".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-m3".to_string(),
            opencode_model_id: "MiniMax-M3".to_string(),
            kv_cache_enabled: false,
            context_window_enabled: true,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(content.contains("export DISABLE_COMPACT=1"));
        assert!(content.contains("export CLAUDE_CODE_MAX_CONTEXT_TOKENS=1000000"));
        assert!(content.contains("export CLAUDE_CODE_AUTO_COMPACT_WINDOW=1000000"));
        assert!(content.contains("DISABLE_COMPACT"));
    }

    #[test]
    fn test_build_env_skips_context_window_when_disabled() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M3".to_string(),
                name: "MiniMax M3".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M3".to_string(),
                context_window: Some(1_000_000),
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M3".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M3-cl-m3".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M3".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-m3".to_string(),
            opencode_model_id: "MiniMax-M3".to_string(),
            kv_cache_enabled: false,
            context_window_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(!content.contains("export DISABLE_COMPACT=1"));
        assert!(!content.contains("export CLAUDE_CODE_MAX_CONTEXT_TOKENS"));
        assert!(!content.contains("export CLAUDE_CODE_AUTO_COMPACT_WINDOW"));
    }

    #[test]
    fn test_ensure_zshrc_source_adds_line() {
        let temp = TempDir::new().unwrap();
        let zshrc = temp.path().join(".zshrc");
        let added = ensure_zshrc_source(&zshrc).unwrap();
        assert!(added);
        let content = fs::read_to_string(&zshrc).unwrap();
        assert!(content.contains("source ~/.cc-switch-tui/aliases.zsh"));

        let added2 = ensure_zshrc_source(&zshrc).unwrap();
        assert!(!added2);
    }
}
