use crate::domain::{ProviderInstance, ProviderTemplate};
use crate::opencode_config;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// 渲染 aliases.zsh 内容（不写盘，不生成 opencode 配置文件）。
/// 供 Web 预览使用。
pub fn render_aliases(instances: &[ProviderInstance], templates: &[ProviderTemplate]) -> String {
    let mut lines = vec![
        "# Auto-generated by cc-switch-tui. Do not edit manually.".to_string(),
        "emulate zsh".to_string(),
    ];

    let all_env_vars = get_all_env_vars(templates);
    lines.push(format_print_env_helper(&all_env_vars));

    for instance in instances {
        if instance.alias.is_empty() {
            continue;
        }
        let env = build_env(instance, templates);
        let function_def = format_function(&instance.alias, &env, instance.kv_cache_enabled);
        lines.push(function_def);
    }

    // 包含 opencode alias 引用（不写 opencode 配置文件本身）
    // 这里我们需要 config_paths，但因为不写盘，所以用占位符
    // 简化：直接复用 build_opencode_aliases 但传空 paths（生成的 alias 引用本地路径）
    let dummy_paths: HashMap<String, PathBuf> = instances
        .iter()
        .filter(|i| !i.alias.is_empty())
        .map(|i| {
            (
                i.alias.clone(),
                PathBuf::from(format!("~/.cc-switch-tui/opencode/{}.json", i.alias)),
            )
        })
        .collect();
    let opencode_lines =
        opencode_config::build_opencode_aliases(instances, templates, &dummy_paths);
    lines.extend(opencode_lines);

    // ys-proxy wrapper — 通过本地代理转发 Claude Code 请求
    // 用 zsh 命令前缀方式临时注入 CC_SWITCH_PROXY_URL（仅本次调用可见，不污染父 shell）；
    // cl-* 函数会在 export 自身 default 之后用该 sentinel 覆盖 ANTHROPIC_BASE_URL。
    lines.push(
        "function ys-proxy {\n  local alias_name=$1\n  shift\n  CC_SWITCH_PROXY_URL=\"http://localhost:7480/ys-proxy/${alias_name}\" $alias_name \"$@\"\n}"
            .to_string(),
    );

    lines.join("\n") + "\n"
}

/// 写入 aliases.zsh 到 dir/aliases.zsh（不生成 opencode 配置文件）。
pub fn write_aliases(dir: &Path, content: &str) -> std::io::Result<PathBuf> {
    fs::create_dir_all(dir)?;
    let path = dir.join("aliases.zsh");
    fs::write(&path, content)?;
    Ok(path)
}

/// 生成 aliases.zsh 文件（同时生成 cl-* 和 oc-* alias，**并**生成 opencode 配置文件）。
/// 保留向后兼容 — main.rs 启动时预生成时仍调用。
pub fn generate_aliases(
    dir: &std::path::Path,
    instances: &[ProviderInstance],
    templates: &[ProviderTemplate],
) -> std::io::Result<()> {
    let content = render_aliases(instances, templates);

    // 同时生成 opencode 配置文件
    let _config_paths = opencode_config::generate_opencode_configs(dir, instances, templates)?;

    write_aliases(dir, &content)?;
    Ok(())
}

fn build_env(
    instance: &ProviderInstance,
    templates: &[ProviderTemplate],
) -> HashMap<String, String> {
    let mut env = HashMap::new();
    if let Some(template) = templates.iter().find(|t| t.id == instance.template_id) {
        env.extend(template.default_env.clone());
        if let Some(model) = template.models.iter().find(|m| m.id == instance.model_id) {
            env.extend(model.env_overrides.clone());
        }
    }
    env.insert("ANTHROPIC_AUTH_TOKEN".to_string(), instance.api_key.clone());
    env.insert(
        "CMUX_PRESERVE_CLAUDE_AUTH_SELECTION_ENV".to_string(),
        "1".to_string(),
    );
    env.insert("CC_SWITCH_ALIAS".to_string(), instance.alias.clone());
    env
}

/// 收集所有需要 unset 的环境变量（来自所有模板）
fn get_all_env_vars(templates: &[ProviderTemplate]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::from([
        "ANTHROPIC_AUTH_TOKEN".to_string(),
        "ANTHROPIC_BASE_URL".to_string(),
        "CMUX_PRESERVE_CLAUDE_AUTH_SELECTION_ENV".to_string(),
        "CC_SWITCH_ALIAS".to_string(),
        "DISABLE_COMPACT".to_string(),
        "CLAUDE_CODE_MAX_CONTEXT_TOKENS".to_string(),
        "CLAUDE_CODE_AUTO_COMPACT_WINDOW".to_string(),
    ]);
    for template in templates {
        set.extend(template.default_env.keys().cloned());
        for model in &template.models {
            set.extend(model.env_overrides.keys().cloned());
        }
    }
    let mut vars: Vec<String> = set.into_iter().collect();
    vars.sort();
    vars
}

/// 生成 __cc_switch_print_env helper 函数定义，用于在 cl-* alias 中打印实际生效的 env
fn format_print_env_helper(all_env_vars: &[String]) -> String {
    let keys_list = all_env_vars
        .iter()
        .map(|k| format!("    {}", k))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "function __cc_switch_print_env {{\n\
         \
  local alias_name=$1\n\
         \
  [[ -n $CC_SWITCH_QUIET ]] && return 0\n\
         \
\n\
         \
  local -a keys=(\n{}\n  )\n\
         \
\n\
         \
  local parts=()\n\
         \
  for k in $keys; do\n\
         \
    local v=${{(P)k}}\n\
         \
    if [[ -z $v ]]; then\n\
         \
      parts+=(\"$k=<unset>\")\n\
         \
    elif [[ $k =~ '(_TOKEN|_API_KEY|_SECRET|_PASSWORD)$' ]]; then\n\
         \
      parts+=(\"$k=<redacted>\")\n\
         \
    else\n\
         \
      parts+=(\"$k=$v\")\n\
         \
    fi\n\
         \
  done\n\
         \
\n\
         \
  echo \"[cc-switch-tui] $alias_name: ${{(j: :)parts}}\" >&2\n\
         }}",
        keys_list
    )
}

fn format_function(name: &str, env: &HashMap<String, String>, kv_cache_enabled: bool) -> String {
    // subshell 内的 export —— 父 shell 不受影响（POSIX 隔离）。
    // subshell exit 后所有 export 销毁；用户 ~/.zshrc 设的同名变量保持不变。
    // 排序后输出，保持生成的 aliases.zsh diff 稳定。
    let mut export_lines: Vec<String> = env
        .iter()
        .map(|(k, v)| format!("    export {}={}", k, shell_escape(v)))
        .collect();
    export_lines.sort();
    let export_block = export_lines.join("\n");

    // ys-proxy 通过命令前缀方式把 CC_SWITCH_PROXY_URL 注入到本次调用；
    // subshell fork 时 inherit 父 shell 的 CC_SWITCH_PROXY_URL，
    // 故此条件判断在 subshell 内仍生效。
    // 限制为 localhost / 127.0.0.1，避免父 shell 中误 export 的 sentinel
    // 把请求路由到任意 host。
    let proxy_override_line = PROXY_OVERRIDE_LINE;

    let claude_cmd = if kv_cache_enabled {
        "command claude --exclude-dynamic-system-prompt-sections --settings '{\"includeGitInstructions\":false}' \"$@\""
    } else {
        "command claude \"$@\""
    };

    format!(
        "function {} {{\n  (\n{}\n{}\n    __cc_switch_print_env {}\n    {}\n  )\n}}",
        name, export_block, proxy_override_line, name, claude_cmd
    )
}

pub(crate) fn shell_escape(s: &str) -> String {
    if s.contains('\'') {
        format!("'{}'", s.replace('\'', "'\"'\"'"))
    } else if s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "_.:-/".contains(c))
    {
        s.to_string()
    } else {
        format!("'{}'", s)
    }
}

/// 在 cl-* 函数 export 自身 default 之后，ys-proxy 通过命令前缀注入的
/// `CC_SWITCH_PROXY_URL` 在此行覆盖 `ANTHROPIC_BASE_URL`。
///
/// 显式限制 sentinel 取值为 `http://localhost:*` / `http://127.0.0.1:*`：
/// 父 shell 中如果误 export 了非本地 URL（例如调试脚本遗留），
/// 不会被 cl-* 函数采用，请求仍走 provider 默认值。
const PROXY_OVERRIDE_LINE: &str = "    [[ $CC_SWITCH_PROXY_URL == http://localhost:* || $CC_SWITCH_PROXY_URL == http://127.0.0.1:* ]] && export ANTHROPIC_BASE_URL=\"$CC_SWITCH_PROXY_URL\"";

/// 检查 zshrc 文件是否包含 source ~/.cc-switch-tui/aliases.zsh
pub fn ensure_zshrc_source(zshrc_path: &std::path::Path) -> std::io::Result<bool> {
    let source_line = "source ~/.cc-switch-tui/aliases.zsh";
    if zshrc_path.exists() {
        let content = fs::read_to_string(zshrc_path)?;
        if content.lines().any(|l| l.trim() == source_line) {
            return Ok(false);
        }
    }
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(zshrc_path)?;
    writeln!(file, "{}", source_line)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{ModelTemplate, ProviderTemplate};
    use std::collections::HashMap;
    use tempfile::TempDir;

    #[test]
    fn test_generate_aliases_creates_file() {
        let temp = TempDir::new().unwrap();
        let instances: Vec<ProviderInstance> = vec![];
        let templates: Vec<ProviderTemplate> = vec![];
        generate_aliases(temp.path(), &instances, &templates).unwrap();
        assert!(temp.path().join("aliases.zsh").exists());
    }

    #[test]
    fn test_generate_aliases_content() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M2.7-highspeed".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed-cl-mini".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
            opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // 新格式：cl-* 函数体外层 ( ... ) 形成 subshell
        assert!(content.contains("function cl-mini {"));
        assert!(content.contains("  (\n") || content.contains("function cl-mini {\n  ("));
        assert!(content.contains("export"));
        assert!(content.contains("command claude \"$@\""));
        assert!(content.contains("  )\n}"));
    }

    #[test]
    fn test_generate_aliases_omits_unset_line() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M2.7-highspeed".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed-cl-mini".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
            opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();

        // cl-* 函数体外层 ( ... ) 形成 subshell —— ( 与 ) 各占独立行
        let cl_block_start = content
            .find("function cl-mini {")
            .expect("function cl-mini 必须存在");
        let cl_block_end = content[cl_block_start..]
            .find("\n}")
            .map(|i| cl_block_start + i)
            .expect("cl-mini 函数体必须以 \\n} 结尾");
        let cl_body = &content[cl_block_start..=cl_block_end];
        assert!(
            cl_body.contains("\n  (\n"),
            "cl-mini 函数体外层 ( 应独占一行（subshell 包裹），实际:\n{cl_body}"
        );
        assert!(
            cl_body.trim_end_matches('\n').ends_with("\n  )"),
            "cl-mini 函数体内层 ) 应独占一行（subshell 闭合），实际:\n{cl_body}"
        );

        // cl-* 块内不应有以 `unset ` 开头的行（subshell 不需要清理）
        let has_unset_line = cl_body
            .lines()
            .any(|l| l.trim_start().starts_with("unset "));
        assert!(
            !has_unset_line,
            "cl-mini 函数体不应生成 unset 行（subshell 隔离已生效），实际:\n{cl_body}"
        );

        // 关键 export 仍存在（核心行为不变）
        assert!(content.contains("export ANTHROPIC_AUTH_TOKEN=sk-test"));
        assert!(content.contains("export CC_SWITCH_ALIAS=cl-mini"));
    }

    #[test]
    fn test_generate_aliases_kv_cache_enabled() {
        let temp = TempDir::new().unwrap();
        let template = ProviderTemplate {
            id: "llama".to_string(),
            name: "Llama.cpp".to_string(),
            default_env: HashMap::new(),
            models: vec![ModelTemplate {
                id: "qwen3-27b".to_string(),
                name: "Qwen3 27B".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "qwen3-27b".to_string(),
            }],
            opencode_provider_id: String::new(),
            opencode_npm: String::new(),
            opencode_base_url: String::new(),
            opencode_env_var: String::new(),
            opencode_models: vec!["qwen3-27b".to_string()],
        };
        let instance = ProviderInstance {
            id: "llama-qwen3-27b-cl-local".to_string(),
            template_id: "llama".to_string(),
            model_id: "qwen3-27b".to_string(),
            api_key: "no-key".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-local".to_string(),
            opencode_model_id: "qwen3-27b".to_string(),
            kv_cache_enabled: true,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // Verify KV cache parameters are present
        assert!(content.contains("--exclude-dynamic-system-prompt-sections"));
        assert!(content.contains("includeGitInstructions"));
        assert!(content.contains("command claude --exclude-dynamic-system-prompt-sections"));
    }

    /// M3[1m] 跟随官方 2026 文档：model id 含 `[1m]` 后缀，env_overrides 自动注入 4 个 ANTHROPIC_DEFAULT_*_MODEL
    #[test]
    fn test_aliases_contain_minimax_m3_1m_model_id() {
        use crate::templates::register_templates;
        let temp = TempDir::new().unwrap();
        let templates = register_templates();
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M3[1m]-cl-m3".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M3[1m]".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-m3".to_string(),
            opencode_model_id: "MiniMax-M3[1m]".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &templates).unwrap();
        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(
            content.contains("MiniMax-M3[1m]"),
            "aliases.zsh 应含 MiniMax-M3[1m] model id（跟随官方文档），实际:\n{content}"
        );
    }

    /// M3[1m] env_overrides 硬编码 CLAUDE_CODE_AUTO_COMPACT_WINDOW=1000000（官方推荐）
    #[test]
    fn test_aliases_contain_auto_compact_window_var() {
        use crate::templates::register_templates;
        let temp = TempDir::new().unwrap();
        let templates = register_templates();
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M3[1m]-cl-m3".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M3[1m]".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-m3".to_string(),
            opencode_model_id: "MiniMax-M3[1m]".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &templates).unwrap();
        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(
            content.contains("CLAUDE_CODE_AUTO_COMPACT_WINDOW=1000000"),
            "M3[1m] env_overrides 应硬编码 CLAUDE_CODE_AUTO_COMPACT_WINDOW=1000000，实际:\n{content}"
        );
    }

    /// Kimi highspeed 档位：model id `kimi-for-coding-highspeed` 应出现在生成的 aliases.zsh 中
    /// （Kimi 后端自动映射到最新高速档位；与 MiniMax M3[1m] 同模式 — per-model env_overrides 注入）
    #[test]
    fn test_aliases_contain_kimi_for_coding_highspeed_model_id() {
        use crate::templates::register_templates;
        let temp = TempDir::new().unwrap();
        let templates = register_templates();
        let instance = ProviderInstance {
            id: "kimi-kimi-for-coding-highspeed-cl-kimi-fast".to_string(),
            template_id: "kimi".to_string(),
            model_id: "kimi-for-coding-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-kimi-fast".to_string(),
            opencode_model_id: "kimi-for-coding-highspeed".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &templates).unwrap();
        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(
            content.contains("kimi-for-coding-highspeed"),
            "aliases.zsh 应含 kimi-for-coding-highspeed model id（Kimi highspeed 档位），实际:\n{content}"
        );
    }

    /// build_env 不再注入 DISABLE_COMPACT / CLAUDE_CODE_MAX_CONTEXT_TOKENS（机制废弃）
    #[test]
    fn test_aliases_do_not_contain_disabled_compact_var() {
        use crate::templates::register_templates;
        let temp = TempDir::new().unwrap();
        let templates = register_templates();
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M3[1m]-cl-m3".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M3[1m]".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-m3".to_string(),
            opencode_model_id: "MiniMax-M3[1m]".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &templates).unwrap();
        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // DISABLE_COMPACT 不应被 build_env 注入（旧 auto-inject 机制已废弃）
        assert!(
            !content.contains("DISABLE_COMPACT="),
            "aliases.zsh 不应含 DISABLE_COMPACT=（auto-inject 机制已废弃），实际:\n{content}"
        );
        assert!(
            !content.contains("CLAUDE_CODE_MAX_CONTEXT_TOKENS="),
            "aliases.zsh 不应含 CLAUDE_CODE_MAX_CONTEXT_TOKENS=，实际:\n{content}"
        );
    }

    #[test]
    fn test_generate_aliases_contains_print_env_helper() {
        let temp = TempDir::new().unwrap();
        let instances: Vec<ProviderInstance> = vec![];
        let templates: Vec<ProviderTemplate> = vec![];
        generate_aliases(temp.path(), &instances, &templates).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(
            content.contains("function __cc_switch_print_env {"),
            "aliases.zsh 应包含 __cc_switch_print_env helper 函数定义"
        );
        assert!(
            content.contains("[[ -n $CC_SWITCH_QUIET ]]") && content.contains("return 0"),
            "helper 应支持 CC_SWITCH_QUIET=1 关闭"
        );
        assert!(
            content.contains("<redacted>"),
            "helper 应将 credential 类变量值替换为 <redacted>"
        );
        assert!(
            content.contains("<unset>"),
            "helper 应将未设置变量标记为 <unset>"
        );
    }

    #[test]
    fn test_generate_aliases_calls_print_env_helper() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M2.7-highspeed".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed-cl-mini".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
            opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        // helper 定义必须在 cl-* 函数之前
        let helper_pos = content
            .find("function __cc_switch_print_env {")
            .expect("应存在 helper 定义");
        let cl_mini_pos = content
            .find("function cl-mini {")
            .expect("应存在 cl-mini 函数");
        assert!(
            helper_pos < cl_mini_pos,
            "helper 函数定义必须在 cl-mini 之前"
        );

        // cl-mini 函数体中必须在 command claude 之前调用 helper
        let cl_mini_body = &content[cl_mini_pos..];
        let cmd_pos = cl_mini_body
            .find("command claude")
            .expect("cl-mini 应包含 command claude");
        let call_pos = cl_mini_body
            .find("__cc_switch_print_env cl-mini")
            .expect("cl-mini 应调用 __cc_switch_print_env");
        assert!(call_pos < cmd_pos, "helper 调用必须在 command claude 之前");
    }

    #[test]
    fn test_print_env_helper_runtime_output() {
        // 在真实的 zsh 中执行 helper，验证 redaction、<unset>、CC_SWITCH_QUIET 行为。
        // 如果系统没有 zsh，则跳过。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert(
            "ANTHROPIC_BASE_URL".to_string(),
            "https://api.minimaxi.com/anthropic".to_string(),
        );
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            }],
            opencode_provider_id: "minimax-cn".to_string(),
            opencode_npm: "@ai-sdk/anthropic".to_string(),
            opencode_base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            opencode_env_var: "MINIMAX_API_KEY".to_string(),
            opencode_models: vec!["MiniMax-M2.7-highspeed".to_string()],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed-cl-mini".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-real-secret-token".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
            opencode_model_id: "MiniMax-M2.7-highspeed".to_string(),
            kv_cache_enabled: false,
        };
        generate_aliases(temp.path(), &[instance], &[template]).unwrap();

        let aliases_path = temp.path().join("aliases.zsh");
        let output_path = temp.path().join("output.txt");
        let quiet_path = temp.path().join("quiet.txt");

        let script = format!(
            "emulate zsh\n\
             source {}\n\
             export ANTHROPIC_AUTH_TOKEN='sk-real-secret-token'\n\
             export CC_SWITCH_ALIAS='cl-mini'\n\
             __cc_switch_print_env cl-mini 2>{}\n\
             cat {}\n",
            aliases_path.display(),
            output_path.display(),
            output_path.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let line = String::from_utf8(out.stdout).unwrap();

        assert!(
            line.contains("[cc-switch-tui] cl-mini:"),
            "输出应包含前缀: {}",
            line
        );
        assert!(
            line.contains("ANTHROPIC_AUTH_TOKEN=<redacted>"),
            "token 应被 redacted: {}",
            line
        );
        assert!(
            !line.contains("sk-real-secret-token"),
            "真实 token 不应泄露: {}",
            line
        );
        assert!(
            line.contains("DISABLE_COMPACT=<unset>"),
            "未设置变量应显示 <unset>: {}",
            line
        );
        assert!(
            line.contains("ANTHROPIC_BASE_URL="),
            "BASE_URL 应被打印: {}",
            line
        );

        // 验证 CC_SWITCH_QUIET=1 时不输出
        let quiet_script = format!(
            "emulate zsh\n\
             source {}\n\
             export ANTHROPIC_AUTH_TOKEN='sk-real-secret-token'\n\
             CC_SWITCH_QUIET=1 __cc_switch_print_env cl-mini 2>{}\n\
             cat {}\n",
            aliases_path.display(),
            quiet_path.display(),
            quiet_path.display(),
        );
        std::fs::write(temp.path().join("run_quiet.zsh"), quiet_script).unwrap();
        let quiet_out = std::process::Command::new("zsh")
            .arg(temp.path().join("run_quiet.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(quiet_out.status.success());
        let quiet_line = String::from_utf8(quiet_out.stdout)
            .unwrap()
            .trim()
            .to_string();
        assert!(
            quiet_line.is_empty(),
            "CC_SWITCH_QUIET=1 时不应有输出，实际: {:?}",
            quiet_line
        );
    }

    #[test]
    fn test_ensure_zshrc_source_adds_line() {
        let temp = TempDir::new().unwrap();
        let zshrc = temp.path().join(".zshrc");
        let added = ensure_zshrc_source(&zshrc).unwrap();
        assert!(added);
        let content = fs::read_to_string(&zshrc).unwrap();
        assert!(content.contains("source ~/.cc-switch-tui/aliases.zsh"));

        let added2 = ensure_zshrc_source(&zshrc).unwrap();
        assert!(!added2);
    }

    // ---- 回归测试：cross-alias env 隔离 ----
    // 详见 feat/alias-env-diagnostic 分支修复：
    // 父 shell 中残留的 ANTHROPIC_BASE_URL 不应污染下一次 cl-* 调用。

    fn fixture(
        template_id: &str,
        model_id: &str,
        alias: &str,
        base_url: &str,
    ) -> (ProviderTemplate, ProviderInstance) {
        let mut env = HashMap::new();
        env.insert("ANTHROPIC_BASE_URL".to_string(), base_url.to_string());
        let template = ProviderTemplate {
            id: template_id.to_string(),
            name: template_id.to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: model_id.to_string(),
                name: model_id.to_string(),
                env_overrides: HashMap::new(),
                opencode_model_id: model_id.to_string(),
            }],
            opencode_provider_id: String::new(),
            opencode_npm: String::new(),
            opencode_base_url: String::new(),
            opencode_env_var: String::new(),
            opencode_models: vec![model_id.to_string()],
        };
        let instance = ProviderInstance {
            id: format!("{template_id}-{model_id}-{alias}"),
            template_id: template_id.to_string(),
            model_id: model_id.to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: alias.to_string(),
            opencode_model_id: model_id.to_string(),
            kv_cache_enabled: false,
        };
        (template, instance)
    }

    #[test]
    fn test_function_body_no_parent_url_leakage() {
        // 静态断言：生成的 cl-* 函数体必须放弃旧的 ${VAR:-default} 回退模式，
        // 并直接 export 自身 default；subshell 隔离替代了原 unset 行清理。
        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();
        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();

        assert!(
            !content.contains("${ANTHROPIC_BASE_URL:-"),
            "cl-* 函数体不应再用 ${{ANTHROPIC_BASE_URL:-...}} 回退模式（这是原 bug 的根因）"
        );
        // 不再有 unset 行 —— subshell 隔离替代了原清理机制
        assert!(
            !content
                .lines()
                .any(|l| l.trim_start().starts_with("unset ")),
            "cl-* 函数体不应生成 unset 行（subshell 隔离已生效），整个文件也不该有"
        );
        assert!(
            content.contains("export ANTHROPIC_BASE_URL=https://api.minimaxi.com/anthropic"),
            "函数体应直接 export 自身 default（不回退父 shell）"
        );
        assert!(
            content.contains(PROXY_OVERRIDE_LINE),
            "cl-* 函数体应通过 CC_SWITCH_PROXY_URL sentinel 允许 ys-proxy 覆盖"
        );
    }

    #[test]
    fn test_ys_proxy_wrapper_uses_command_prefix_sentinel() {
        // 静态断言：ys-proxy wrapper 必须用命令前缀形式（旧 subshell 形式是 bug 路径）。
        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();
        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();

        assert!(
            content.contains(
                "CC_SWITCH_PROXY_URL=\"http://localhost:7480/ys-proxy/${alias_name}\" $alias_name \"$@\""
            ),
            "ys-proxy wrapper 必须用命令前缀方式注入 CC_SWITCH_PROXY_URL"
        );
        assert!(
            !content.contains("(\n    export ANTHROPIC_BASE_URL=\"http://localhost:7480/ys-proxy"),
            "ys-proxy wrapper 不应再使用 subshell 形式（旧 bug 路径）"
        );
    }

    #[test]
    fn test_function_body_subshell_isolates_claude_url() {
        // 真实 zsh 回归：subshell 隔离 —— cl-* 调用结束后父 shell 不残留任何
        // ANTHROPIC_* / API_TIMEOUT_MS / CC_SWITCH_ALIAS env；且即使先后调用
        // cl-kimi 与 cl-mini，cl-mini 仍传给 claude minimaxi 的 URL。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let (mini_tmpl, mini_inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        let (kimi_tmpl, kimi_inst) = fixture(
            "kimi",
            "kimi-coding",
            "cl-kimi",
            "https://api.kimi.com/coding/",
        );
        generate_aliases(
            temp.path(),
            &[mini_inst, kimi_inst],
            &[mini_tmpl, kimi_tmpl],
        )
        .unwrap();

        // 用 stub 替换 PATH 中的 claude，避免依赖真实二进制。
        let bin_dir = temp.path().join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        let claude_stub = bin_dir.join("claude");
        std::fs::write(
            &claude_stub,
            "#!/bin/zsh\necho \"CLAUDE_URL=$ANTHROPIC_BASE_URL\"\nexit 0\n",
        )
        .unwrap();
        std::fs::set_permissions(
            &claude_stub,
            std::os::unix::fs::PermissionsExt::from_mode(0o755),
        )
        .unwrap();

        let kimi_out = temp.path().join("kimi.txt");
        let mini_out = temp.path().join("mini.txt");
        let poll_out = temp.path().join("poll.txt");
        let aliases_path = temp.path().join("aliases.zsh");
        let script = format!(
            "emulate zsh\n\
             unset ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL ANTHROPIC_DEFAULT_HAIKU_MODEL \\\n\
                   ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL \\\n\
                   ANTHROPIC_MODEL API_TIMEOUT_MS CC_SWITCH_ALIAS \\\n\
                   CLAUDE_CODE_MAX_CONTEXT_TOKENS CLAUDE_CODE_AUTO_COMPACT_WINDOW \\\n\
                   DISABLE_COMPACT CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC \\\n\
                   CMUX_PRESERVE_CLAUDE_AUTH_SELECTION_ENV\n\
             export PATH=\"{bin}:$PATH\"\n\
             source {aliases}\n\
             cl-kimi >{kimi} 2>&1\n\
             cl-mini >{mini} 2>&1\n\
             env | grep -E '^(ANTHROPIC|API_TIMEOUT_MS|CC_SWITCH_ALIAS)=' >{poll} 2>&1 || true\n",
            bin = bin_dir.display(),
            aliases = aliases_path.display(),
            kimi = kimi_out.display(),
            mini = mini_out.display(),
            poll = poll_out.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let kimi_combined = std::fs::read_to_string(&kimi_out).unwrap();
        let mini_combined = std::fs::read_to_string(&mini_out).unwrap();

        // 健全性检查：cl-kimi 自身用 kimi URL
        assert!(
            kimi_combined.contains("CLAUDE_URL=https://api.kimi.com/coding/"),
            "cl-kimi 应使用 kimi URL，实际:\n{kimi_combined}"
        );

        // 关键回归断言：cl-mini 必须用 minimaxi URL（不受 cl-kimi 残留影响）
        assert!(
            mini_combined.contains("CLAUDE_URL=https://api.minimaxi.com/anthropic"),
            "cl-mini 在父 shell 被污染时应仍用 minimaxi URL，实际:\n{mini_combined}"
        );
        assert!(
            !mini_combined.contains("kimi.com"),
            "cl-mini 不应把 kimi URL 传给 claude，实际:\n{mini_combined}"
        );

        // subshell 隔离的核心断言：两次调用结束后父 shell 不残留关键 env
        let poll = std::fs::read_to_string(&poll_out).unwrap();
        assert!(
            poll.is_empty(),
            "subshell 隔离后父 shell 应无 ANTHROPIC_* / API_TIMEOUT_MS / CC_SWITCH_ALIAS 残留，实际:\n{poll}"
        );
    }

    #[test]
    fn test_function_body_no_parent_shell_pollution() {
        // 专注验证 subshell 隔离：单次 cl-* 调用结束后，父 shell 不残留
        // 任何 ANTHROPIC_* / API_TIMEOUT_MS / CC_SWITCH_* env。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();

        // stub claude：仅打印一行 OK，避免依赖真实二进制
        let bin_dir = temp.path().join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        let claude_stub = bin_dir.join("claude");
        std::fs::write(&claude_stub, "#!/bin/zsh\necho \"OK\"\nexit 0\n").unwrap();
        std::fs::set_permissions(
            &claude_stub,
            std::os::unix::fs::PermissionsExt::from_mode(0o755),
        )
        .unwrap();

        let poll_out = temp.path().join("poll.txt");
        let aliases_path = temp.path().join("aliases.zsh");
        let script = format!(
            "emulate zsh\n\
             unset ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL ANTHROPIC_DEFAULT_HAIKU_MODEL \\\n\
                   ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL \\\n\
                   ANTHROPIC_MODEL API_TIMEOUT_MS CC_SWITCH_ALIAS \\\n\
                   CLAUDE_CODE_MAX_CONTEXT_TOKENS CLAUDE_CODE_AUTO_COMPACT_WINDOW \\\n\
                   DISABLE_COMPACT CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC \\\n\
                   CMUX_PRESERVE_CLAUDE_AUTH_SELECTION_ENV\n\
             export PATH=\"{bin}:$PATH\"\n\
             source {aliases}\n\
             cl-mini >/dev/null 2>&1\n\
             env | grep -E '^(ANTHROPIC|API_TIMEOUT_MS|CC_SWITCH)' >{poll} 2>&1 || true\n",
            bin = bin_dir.display(),
            aliases = aliases_path.display(),
            poll = poll_out.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let poll = std::fs::read_to_string(&poll_out).unwrap();
        assert!(
            poll.is_empty(),
            "cl-* 调用结束后父 shell 应无 ANTHROPIC_* / API_TIMEOUT_MS / CC_SWITCH_* 残留，实际:\n{poll}"
        );
    }

    #[test]
    fn test_function_body_preserves_zshrc_exports() {
        // 验证用户在父 shell export 的 MINIMAX_API_KEY（模拟 ~/.zshrc 设的值）
        // 不被 cl-* 调用破坏。subshell 内 export 不应影响父 shell 同名变量。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();

        let bin_dir = temp.path().join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        let claude_stub = bin_dir.join("claude");
        std::fs::write(&claude_stub, "#!/bin/zsh\necho \"OK\"\nexit 0\n").unwrap();
        std::fs::set_permissions(
            &claude_stub,
            std::os::unix::fs::PermissionsExt::from_mode(0o755),
        )
        .unwrap();

        let result_out = temp.path().join("after.txt");
        let aliases_path = temp.path().join("aliases.zsh");
        let script = format!(
            "emulate zsh\n\
             export MINIMAX_API_KEY=zshrc_value_should_survive\n\
             export PATH=\"{bin}:$PATH\"\n\
             source {aliases}\n\
             cl-mini >/dev/null 2>&1\n\
             echo \"AFTER=$MINIMAX_API_KEY\" >{result}\n",
            bin = bin_dir.display(),
            aliases = aliases_path.display(),
            result = result_out.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let result = std::fs::read_to_string(&result_out).unwrap();
        assert!(
            result.contains("AFTER=zshrc_value_should_survive"),
            "cl-* 调用后用户 ~/.zshrc 设的 MINIMAX_API_KEY 应保持原值，实际:\n{result}"
        );
    }

    #[test]
    fn test_function_body_subshell_reads_ys_proxy_sentinel() {
        // 验证 subshell 能读到父 shell 的 CC_SWITCH_PROXY_URL sentinel，
        // 且 PROXY_OVERRIDE_LINE 条件判断在 subshell 内生效 —— 把
        // ANTHROPIC_BASE_URL 覆盖为本地 proxy URL。
        //
        // 与 test_ys_proxy_sentinel_overrides_anthropic_base_url 不同：本测试
        // 不通过 ys-proxy wrapper，而是用户预先 export CC_SWITCH_PROXY_URL，
        // 直接调 cl-mini —— 更精确隔离 subshell 读 sentinel 的能力。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();

        let bin_dir = temp.path().join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        let claude_stub = bin_dir.join("claude");
        std::fs::write(
            &claude_stub,
            "#!/bin/zsh\necho \"CLAUDE_URL=$ANTHROPIC_BASE_URL\"\nexit 0\n",
        )
        .unwrap();
        std::fs::set_permissions(
            &claude_stub,
            std::os::unix::fs::PermissionsExt::from_mode(0o755),
        )
        .unwrap();

        let out_file = temp.path().join("out.txt");
        let proxy_after_out = temp.path().join("proxy_after.txt");
        let aliases_path = temp.path().join("aliases.zsh");
        let script = format!(
            "emulate zsh\n\
             export PATH=\"{bin}:$PATH\"\n\
             source {aliases}\n\
             export CC_SWITCH_PROXY_URL=http://localhost:7480/ys-proxy/cl-mini\n\
             cl-mini >{out} 2>&1\n\
             echo AFTER_PROXY=$CC_SWITCH_PROXY_URL >{after}\n",
            bin = bin_dir.display(),
            aliases = aliases_path.display(),
            out = out_file.display(),
            after = proxy_after_out.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let combined = std::fs::read_to_string(&out_file).unwrap();
        assert!(
            combined.contains("CLAUDE_URL=http://localhost:7480/ys-proxy/cl-mini"),
            "subshell 内应读到 CC_SWITCH_PROXY_URL 并覆盖 ANTHROPIC_BASE_URL，实际:\n{combined}"
        );
        // 脚本级 export 的 CC_SWITCH_PROXY_URL 在 cl-* 调用后应保持原值
        // （这是用户在脚本里自己设的，cl-* 不应擦除）。注意不能用 std::env::var
        // ——它看的是 Rust test runner 进程的环境，跟 zsh 子进程的父 shell 完全无关。
        let proxy_after = std::fs::read_to_string(&proxy_after_out).unwrap();
        assert!(
            proxy_after.contains("AFTER_PROXY=http://localhost:7480/ys-proxy/cl-mini"),
            "cl-* 不应擦除用户预先 export 的 CC_SWITCH_PROXY_URL，实际:\n{proxy_after}"
        );
    }

    #[test]
    fn test_ys_proxy_sentinel_overrides_anthropic_base_url() {
        // 真实 zsh 回归：ys-proxy cl-mini 应把本地代理 URL 传给 claude，
        // 且调用结束后父 shell 不残留 CC_SWITCH_PROXY_URL。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();

        let bin_dir = temp.path().join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        let claude_stub = bin_dir.join("claude");
        std::fs::write(
            &claude_stub,
            "#!/bin/zsh\necho \"CLAUDE_URL=$ANTHROPIC_BASE_URL\"\nexit 0\n",
        )
        .unwrap();
        std::fs::set_permissions(
            &claude_stub,
            std::os::unix::fs::PermissionsExt::from_mode(0o755),
        )
        .unwrap();

        let out_file = temp.path().join("out.txt");
        let proxy_after_out = temp.path().join("proxy_after.txt");
        let aliases_path = temp.path().join("aliases.zsh");
        let script = format!(
            "emulate zsh\n\
             export PATH=\"{bin}:$PATH\"\n\
             source {aliases}\n\
             ys-proxy cl-mini >{out} 2>&1\n\
             echo AFTER_PROXY=$CC_SWITCH_PROXY_URL >{after}\n",
            bin = bin_dir.display(),
            aliases = aliases_path.display(),
            out = out_file.display(),
            after = proxy_after_out.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let combined = std::fs::read_to_string(&out_file).unwrap();
        assert!(
            combined.contains("CLAUDE_URL=http://localhost:7480/ys-proxy/cl-mini"),
            "ys-proxy 应把本地代理 URL 传给 claude，实际:\n{combined}"
        );

        // ys-proxy 用命令前缀注入 CC_SWITCH_PROXY_URL（POSIX prefix-env），
        // 退出后 sentinel 应随之销毁，zsh 脚本级 shell 不应残留它。
        // 注意不能用 std::env::var ——它看的是 Rust test runner 进程，
        // 跟 zsh 子进程的父 shell 完全无关。
        let proxy_after = std::fs::read_to_string(&proxy_after_out).unwrap();
        assert!(
            proxy_after.contains("AFTER_PROXY=") && !proxy_after.contains("localhost:7480"),
            "ys-proxy 调用结束后脚本级 shell 不应残留 CC_SWITCH_PROXY_URL，实际:\n{proxy_after}"
        );
    }

    #[test]
    fn test_ys_proxy_rejects_non_localhost_sentinel_value() {
        // 安全收紧：父 shell 中预先 export 一个非 localhost 的 CC_SWITCH_PROXY_URL，
        // 调用 cl-mini 验证它不会被采用（请求仍走 provider 默认值）。
        if std::process::Command::new("zsh")
            .arg("--version")
            .output()
            .is_err()
        {
            return;
        }

        let temp = TempDir::new().unwrap();
        let (tmpl, inst) = fixture(
            "minimax",
            "MiniMax-M2.7-highspeed",
            "cl-mini",
            "https://api.minimaxi.com/anthropic",
        );
        generate_aliases(temp.path(), &[inst], &[tmpl]).unwrap();

        let bin_dir = temp.path().join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        let claude_stub = bin_dir.join("claude");
        std::fs::write(
            &claude_stub,
            "#!/bin/zsh\necho \"CLAUDE_URL=$ANTHROPIC_BASE_URL\"\nexit 0\n",
        )
        .unwrap();
        std::fs::set_permissions(
            &claude_stub,
            std::os::unix::fs::PermissionsExt::from_mode(0o755),
        )
        .unwrap();

        let out_file = temp.path().join("out.txt");
        let aliases_path = temp.path().join("aliases.zsh");
        let script = format!(
            "emulate zsh\n\
             export PATH=\"{bin}:$PATH\"\n\
             source {aliases}\n\
             export CC_SWITCH_PROXY_URL=\"https://attacker.example.com/proxy\"\n\
             cl-mini >{out} 2>&1\n",
            bin = bin_dir.display(),
            aliases = aliases_path.display(),
            out = out_file.display(),
        );
        std::fs::write(temp.path().join("run.zsh"), script).unwrap();
        let out = std::process::Command::new("zsh")
            .arg(temp.path().join("run.zsh"))
            .output()
            .expect("zsh should be available");
        assert!(
            out.status.success(),
            "zsh 执行失败: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let combined = std::fs::read_to_string(&out_file).unwrap();
        assert!(
            combined.contains("CLAUDE_URL=https://api.minimaxi.com/anthropic"),
            "非 localhost 的 CC_SWITCH_PROXY_URL 必须被拒绝，cl-mini 应走默认 URL，实际:\n{combined}"
        );
        assert!(
            !combined.contains("attacker.example.com"),
            "非 localhost 的 sentinel 不应被采用，实际:\n{combined}"
        );
    }
}
