use crate::domain::{ProviderInstance, ProviderTemplate};
use std::collections::HashMap;
use std::fs;
use std::io::Write;

/// 生成 aliases.zsh 文件
pub fn generate_aliases(
    dir: &std::path::Path,
    instances: &[ProviderInstance],
    templates: &[ProviderTemplate],
    current_instance_id: Option<&str>,
) -> std::io::Result<()> {
    let mut lines = vec!["# Auto-generated by cc-switch-tui. Do not edit manually.".to_string()];

    for instance in instances {
        if instance.alias.is_empty() {
            continue;
        }
        let env = build_env(instance, templates);
        let alias_line = format_alias_cmd(&instance.alias, &env);
        lines.push(alias_line);
    }

    if let Some(id) = current_instance_id {
        if let Some(instance) = instances.iter().find(|i| i.id == id && !i.alias.is_empty()) {
            let env = build_env(instance, templates);
            let alias_line = format_alias_cmd("claude", &env);
            lines.push(alias_line);
        }
    }

    fs::create_dir_all(dir)?;
    let path = dir.join("aliases.zsh");
    fs::write(path, lines.join("\n") + "\n")?;
    Ok(())
}

fn build_env(instance: &ProviderInstance, templates: &[ProviderTemplate]) -> HashMap<String, String> {
    let mut env = HashMap::new();
    if let Some(template) = templates.iter().find(|t| t.id == instance.template_id) {
        env.extend(template.default_env.clone());
        if let Some(model) = template.models.iter().find(|m| m.id == instance.model_id) {
            env.extend(model.env_overrides.clone());
        }
    }
    env.insert("ANTHROPIC_AUTH_TOKEN".to_string(), instance.api_key.clone());
    env
}

fn format_alias_cmd(name: &str, env: &HashMap<String, String>) -> String {
    let mut pairs: Vec<_> = env.iter().collect();
    pairs.sort_by(|a, b| a.0.cmp(b.0));
    let env_str = pairs
        .iter()
        .map(|(k, v)| format!("{}={}", k, shell_escape(v)))
        .collect::<Vec<_>>()
        .join(" ");
    format!("alias {}='{} claude'", name, env_str)
}

fn shell_escape(s: &str) -> String {
    if s.contains('\'') {
        format!("'{}'", s.replace('\'', "'\"'\"'"))
    } else if s.chars().all(|c| c.is_ascii_alphanumeric() || "_.:-/".contains(c)) {
        s.to_string()
    } else {
        format!("'{}'", s)
    }
}

/// 检查 zshrc 文件是否包含 source ~/.cc-switch-tui/aliases.zsh
pub fn ensure_zshrc_source(zshrc_path: &std::path::Path) -> std::io::Result<bool> {
    let source_line = "source ~/.cc-switch-tui/aliases.zsh";
    if zshrc_path.exists() {
        let content = fs::read_to_string(zshrc_path)?;
        if content.lines().any(|l| l.trim() == source_line) {
            return Ok(false);
        }
    }
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(zshrc_path)?;
    writeln!(file, "{}", source_line)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{ModelTemplate, ProviderTemplate};
    use std::collections::HashMap;
    use tempfile::TempDir;

    #[test]
    fn test_generate_aliases_creates_file() {
        let temp = TempDir::new().unwrap();
        let instances: Vec<ProviderInstance> = vec![];
        let templates: Vec<ProviderTemplate> = vec![];
        generate_aliases(temp.path(), &instances, &templates, None).unwrap();
        assert!(temp.path().join("aliases.zsh").exists());
    }

    #[test]
    fn test_generate_aliases_content() {
        let temp = TempDir::new().unwrap();
        let mut env = HashMap::new();
        env.insert("ANTHROPIC_BASE_URL".to_string(), "https://api.minimaxi.com/anthropic".to_string());
        let template = ProviderTemplate {
            id: "minimax".to_string(),
            name: "MiniMax".to_string(),
            default_env: env,
            models: vec![ModelTemplate {
                id: "MiniMax-M2.7-highspeed".to_string(),
                name: "MiniMax M2.7 Highspeed".to_string(),
                env_overrides: HashMap::new(),
            }],
        };
        let instance = ProviderInstance {
            id: "minimax-MiniMax-M2.7-highspeed".to_string(),
            template_id: "minimax".to_string(),
            model_id: "MiniMax-M2.7-highspeed".to_string(),
            api_key: "sk-test".to_string(),
            created_at: chrono::Utc::now(),
            alias: "cl-mini".to_string(),
        };
        generate_aliases(
            temp.path(),
            &[instance],
            &[template],
            Some("minimax-MiniMax-M2.7-highspeed"),
        ).unwrap();

        let content = std::fs::read_to_string(temp.path().join("aliases.zsh")).unwrap();
        assert!(content.contains("alias cl-mini="));
        assert!(content.contains("alias claude="));
        assert!(content.contains("ANTHROPIC_BASE_URL=https://api.minimaxi.com/anthropic"));
        assert!(content.contains("ANTHROPIC_AUTH_TOKEN=sk-test"));
    }

    #[test]
    fn test_ensure_zshrc_source_adds_line() {
        let temp = TempDir::new().unwrap();
        let zshrc = temp.path().join(".zshrc");
        let added = ensure_zshrc_source(&zshrc).unwrap();
        assert!(added);
        let content = fs::read_to_string(&zshrc).unwrap();
        assert!(content.contains("source ~/.cc-switch-tui/aliases.zsh"));

        let added2 = ensure_zshrc_source(&zshrc).unwrap();
        assert!(!added2);
    }
}
